//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewellery_01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jewellery_01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _124090_abstract_shiny_gold_metal_texture_background {
            get {
                object obj = ResourceManager.GetObject("124090-abstract-shiny-gold-metal-texture-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _124090_abstract_shiny_gold_metal_texture_background1 {
            get {
                object obj = ResourceManager.GetObject("124090-abstract-shiny-gold-metal-texture-background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _187_1873795_free_logos_png_square_transparent_png {
            get {
                object obj = ResourceManager.GetObject("187-1873795_free-logos-png-square-transparent-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5a2135ffa566e6_2301536615121259516775 {
            get {
                object obj = ResourceManager.GetObject("5a2135ffa566e6.2301536615121259516775", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _62495538 {
            get {
                object obj = ResourceManager.GetObject("62495538", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _640_02952303en_Masterfile {
            get {
                object obj = ResourceManager.GetObject("640-02952303en_Masterfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _947b8bc6cbec8d4a7a178d878b94752a {
            get {
                object obj = ResourceManager.GetObject("947b8bc6cbec8d4a7a178d878b94752a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _947b8bc6cbec8d4a7a178d878b94752a1 {
            get {
                object obj = ResourceManager.GetObject("947b8bc6cbec8d4a7a178d878b94752a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_dark_design_geometric_background_decor_golden_lines_with_copy_space_for_text_luxury_style_free_vector {
            get {
                object obj = ResourceManager.GetObject("abstract-dark-design-geometric-background-decor-golden-lines-with-copy-space-for-" +
                        "text-luxury-style-free-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_gold_glossy_stylish_background_vector {
            get {
                object obj = ResourceManager.GetObject("abstract-gold-glossy-stylish-background-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_gold_glossy_stylish_background_vector1 {
            get {
                object obj = ResourceManager.GetObject("abstract-gold-glossy-stylish-background-vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b06391295d24b9de69edabbd4fee439a {
            get {
                object obj = ResourceManager.GetObject("b06391295d24b9de69edabbd4fee439a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner2_3 {
            get {
                object obj = ResourceManager.GetObject("banner2-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner2_31 {
            get {
                object obj = ResourceManager.GetObject("banner2-31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner2_32 {
            get {
                object obj = ResourceManager.GetObject("banner2-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner2_33 {
            get {
                object obj = ResourceManager.GetObject("banner2-33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamond_gemstone_black_icon_transparent_png_svg_vector_37 {
            get {
                object obj = ResourceManager.GetObject("diamond-gemstone-black-icon-transparent-png-svg-vector-37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamond_gemstone_black_icon_transparent_png_svg_vector_371 {
            get {
                object obj = ResourceManager.GetObject("diamond-gemstone-black-icon-transparent-png-svg-vector-371", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamond_gemstone_black_icon_transparent_png_svg_vector_372 {
            get {
                object obj = ResourceManager.GetObject("diamond-gemstone-black-icon-transparent-png-svg-vector-372", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamond_gemstone_black_icon_transparent_png_svg_vector_373 {
            get {
                object obj = ResourceManager.GetObject("diamond-gemstone-black-icon-transparent-png-svg-vector-373", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamond_gemstone_black_icon_transparent_png_svg_vector_374 {
            get {
                object obj = ResourceManager.GetObject("diamond-gemstone-black-icon-transparent-png-svg-vector-374", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamond_gemstone_black_icon_transparent_png_svg_vector_375 {
            get {
                object obj = ResourceManager.GetObject("diamond-gemstone-black-icon-transparent-png-svg-vector-375", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dot_stainless_steel_led_signal_lamps_alan_butcher_components_24 {
            get {
                object obj = ResourceManager.GetObject("dot-stainless-steel-led-signal-lamps-alan-butcher-components-24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elegant_logo_design_free_logos_creator_make_online_classy_logo_design_11562898542pjpxwxoefy {
            get {
                object obj = ResourceManager.GetObject("elegant-logo-design-free-logos-creator-make-online-classy-logo-design-11562898542" +
                        "pjpxwxoefy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ffdb7b09281029297629c7caa5123458 {
            get {
                object obj = ResourceManager.GetObject("ffdb7b09281029297629c7caa5123458", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ffdb7b09281029297629c7caa51234581 {
            get {
                object obj = ResourceManager.GetObject("ffdb7b09281029297629c7caa51234581", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1222335712_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1222335712-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_157305526_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-157305526-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_172356191_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-172356191-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_515199416_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-515199416-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_515199416_612x6121 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-515199416-612x6121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_652263900_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-652263900-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_652263900_612x6121 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-652263900-612x6121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jewel {
            get {
                object obj = ResourceManager.GetObject("jewel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_diamond_logo_template_png_image_1548443 {
            get {
                object obj = ResourceManager.GetObject("pngtree-diamond-logo-template-png-image_1548443", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_diamond_logo_template_png_image_15484431 {
            get {
                object obj = ResourceManager.GetObject("pngtree-diamond-logo-template-png-image_15484431", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timantti_diamond_project_arctic_star_exploration_8 {
            get {
                object obj = ResourceManager.GetObject("timantti-diamond-project-arctic-star-exploration-8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_10_15_at_22_38_22 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-10-15 at 22.38.22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Womens_Jewellery_Trends_For_2022 {
            get {
                object obj = ResourceManager.GetObject("Womens-Jewellery-Trends-For-2022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Womens_Jewellery_Trends_For_20221 {
            get {
                object obj = ResourceManager.GetObject("Womens-Jewellery-Trends-For-20221", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
